<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:include filename="$(find realsense2_description)/urdf/_d435i.urdf.xacro"/>

    <xacro:property name="chassis_length" value="0.280"/>
    <xacro:property name="chassis_width" value="0.216"/>
    <xacro:property name="chassis_height" value="0.006"/>
    <xacro:property name="chassis_mass" value="0.25"/>
    <xacro:property name="wheel_radius" value="0.032"/>
    <xacro:property name="wheel_thickness" value="0.006"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.261"/>
    <xacro:property name="wheel_offset_y" value="0.114"/>
    <xacro:property name="wheel_offset_z" value="0.0255"/>
    <xacro:property name="caster_wheel_radius" value="0.0255"/>
    <xacro:property name="caster_wheel_mass" value="0.2"/>
    <xacro:property name="caster_wheel_offset_x" value="0.035"/>
    <xacro:property name="caster_wheel_offset_z" value="${caster_wheel_radius}"/>
    <xacro:property name="motor_radius" value="0.0125"/>
    <xacro:property name="motor_length" value="0.075"/>
    <xacro:property name="motor_mass" value="0.1"/>
    <xacro:property name="motor_offset_y" value="0.071"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- LEFT MOTOR LINK -->
    <joint name="left_motor_joint" type="fixed">
        <parent link="base_link"/>
        <child link="left_motor"/>
        <origin xyz="0 ${motor_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_motor">
        <visual>
            <geometry>
                <cylinder radius="${motor_radius}" length="${motor_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${motor_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${motor_mass}" length="${motor_length}" radius="${motor_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_motor">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- RIGHT MOTOR LINK -->
    <joint name="right_motor_joint" type="fixed">
        <parent link="base_link"/>
        <child link="right_motor"/>
        <origin xyz="0 ${-motor_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_motor">
        <visual>
            <geometry>
                <cylinder radius="${motor_radius}" length="${motor_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${motor_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${motor_mass}" length="${motor_length}" radius="${motor_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_motor">
        <material>Gazebo/Blue</material>
    </gazebo> 


    <!-- CASTER WHEEL LINK -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${-caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <!-- Camera Links -->

    <xacro:sensor_d435i parent="base_link" use_nominal_extrinsics="false">
        <origin xyz="0 0 .0454" rpy="0 0 0"/>
    </xacro:sensor_d435i> 

    <gazebo reference="camera_link">
      <material>Gazebo/White</material>
    </gazebo> 

    <joint name="camera_mount_joint" type="fixed">
        <parent link="chassis"/>
        <child link="camera_mount_link"/>
        <origin xyz="0.130 0 0.007" rpy="0 0 0"/>
    </joint>

    <!-- Camera Mounts -->

    <link name="camera_mount_link">
        <visual>
            <origin xyz="0.130 0 0.007" rpy="0 0 0"/>
            <geometry>
                <box size="0.006 0.0254 0.017"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0.130 0 0.007" rpy="0 0 0"/>
            <geometry>
                <box size="0.006 0.0254 0.017"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.006" y="0.0254" z="0.017">
            <origin xyz="0.130 0 0.007" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>



</robot>